/* =========================================================================
   AUDIO MAP — AUTO-GENERATED by scripts/generate_audio.js (do not edit by hand)
   Key -> { text spoken (== text shown on screen), style, static mp3 path }
   ========================================================================= */
export const AUDIO_MAP = {
  "wonder_1": {
    text: "Zara and Leo's class is running a book sale. A book and a bookmark cost $11 together, and the book costs exactly $10 more than the bookmark. Most people blurt out that the bookmark costs $1, but a quick sketch reveals something surprising!",
    style: "statement",
    file: "/assets/audio/wonder_1_zara_and_leos_class_is_running.mp3"
  },
  "wonder_2": {
    text: "How can we turn a wordy problem into a picture or an equation that gives the right answer every time?",
    style: "question",
    file: "/assets/audio/wonder_2_how_can_we_turn_a_wordy.mp3"
  },
  "story_1": {
    text: "Word problems are little stories with numbers hiding inside. Imagine a book and a bookmark cost $11 together, and the book costs $10 more than the bookmark. How much is the bookmark? Before we calculate anything, we must understand the story.",
    style: "statement",
    file: "/assets/audio/story_1_word_problems_are_little_stories_with.mp3"
  },
  "story_2": {
    text: "Ask three detective questions. What is given? What am I asked to find? And how are the quantities related? Underline the facts, circle the question, and ignore details that do not change the answer.",
    style: "emphasis",
    file: "/assets/audio/story_2_ask_three_detective_questions_what_is.mp3"
  },
  "story_3": {
    text: "Every problem has a mystery quantity, so give it a letter! Let b stand for the price of the bookmark in dollars. Then the book costs b + 10, because it is $10 more. Always say what your letter means, and include its unit.",
    style: "statement",
    file: "/assets/audio/story_3_every_problem_has_a_mystery_quantity.mp3"
  },
  "story_4": {
    text: "Draw one bar for each quantity. The bookmark is a short bar, b. The book is the same bar plus an extra piece worth $10. Together, the two bars make $11. Now the whole relationship is visible at a glance!",
    style: "emphasis",
    file: "/assets/audio/story_4_draw_one_bar_for_each_quantity.mp3"
  },
  "story_5": {
    text: "Tables help when something changes step by step. A taxi charges $3 to start, plus $2 for every kilometre. List 1, 2, 3 and 4 kilometres, and the fare goes up by 2 each time. Spot the pattern, and you can write the rule.",
    style: "statement",
    file: "/assets/audio/story_5_tables_help_when_something_changes_step.mp3"
  },
  "story_6": {
    text: "Now translate words into symbols. Three more than twice a number is 17 becomes 2n + 3 = 17. More than means add, twice means multiply by 2, and is means equals. Read your equation back in words to check that it tells the same story.",
    style: "emphasis",
    file: "/assets/audio/story_6_now_translate_words_into_symbols_three.mp3"
  },
  "story_7": {
    text: "Time to solve. The bar model gives b + b + 10 = 11, so 2b = 1 and b = 0.5. The bookmark costs 50 cents and the book costs $10.50. Check it: 0.50 + 10.50 = 11, and the book is exactly $10 more. It fits the story, so the answer makes sense!",
    style: "encouragement",
    file: "/assets/audio/story_7_time_to_solve_the_bar_model.mp3"
  },
  "story_8": {
    text: "Awesome job! You can now understand a problem, name the unknown, and represent it with a bar model, a table, or an equation. Step into the lab to highlight clues, build models, and solve puzzles!",
    style: "celebration",
    file: "/assets/audio/story_8_awesome_job_you_can_now_understand.mp3"
  },
  "sim_1_1": {
    text: "Zara's class runs a fun fair. Pick a highlighter and tap the clues: blue for given, red for asked, and gold for related.",
    style: "encouragement",
    file: "/assets/audio/sim_1_1_zaras_class_runs_a_fun_fair.mp3"
  },
  "sim_1_2": {
    text: "Leo and Mia collect cans. Highlight the clues again, and watch out for details that do not help!",
    style: "encouragement",
    file: "/assets/audio/sim_1_2_leo_and_mia_collect_cans_highlight.mp3"
  },
  "sim_1_3": {
    text: "Phone plans hide a pattern. Find the fixed fee, the price per message, and the question asked.",
    style: "encouragement",
    file: "/assets/audio/sim_1_3_phone_plans_hide_a_pattern_find.mp3"
  },
  "sim_2_1": {
    text: "Build a bar model! Give Mia and Sam the right number of equal boxes, then reveal the value of one box.",
    style: "statement",
    file: "/assets/audio/sim_2_1_build_a_bar_model_give_mia.mp3"
  },
  "sim_2_2": {
    text: "Complete the missing heights for the sunflower, then choose the rule that matches the pattern.",
    style: "statement",
    file: "/assets/audio/sim_2_2_complete_the_missing_heights_for_the.mp3"
  },
  "sim_2_3": {
    text: "Translate words into symbols! Tap the tiles in order to build an equation that tells the same story.",
    style: "statement",
    file: "/assets/audio/sim_2_3_translate_words_into_symbols_tap_the.mp3"
  },
  "sim_3_1": {
    text: "Kai and his dad have ages that fit a bar model. Use the model to work out Kai's age.",
    style: "question",
    file: "/assets/audio/sim_3_1_kai_and_his_dad_have_ages.mp3"
  },
  "sim_3_2": {
    text: "A taxi fare follows the rule: 3 plus 2 times the kilometres. The fare was $25. How far did the taxi go?",
    style: "question",
    file: "/assets/audio/sim_3_2_a_taxi_fare_follows_the_rule.mp3"
  },
  "sim_3_3": {
    text: "Ravi made a mistake while solving. Find the error, then work out the correct value of x.",
    style: "question",
    file: "/assets/audio/sim_3_3_ravi_made_a_mistake_while_solving.mp3"
  },
  "fb_correct": {
    text: "Correct! Excellent problem solving!",
    style: "celebration",
    file: "/assets/audio/fb_correct_correct_excellent_problem_solving.mp3"
  },
  "fb_wrong": {
    text: "Not quite! Look at the story again.",
    style: "encouragement",
    file: "/assets/audio/fb_wrong_not_quite_look_at_the_story.mp3"
  },
  "sim_success": {
    text: "Awesome! You cracked it!",
    style: "celebration",
    file: "/assets/audio/sim_success_awesome_you_cracked_it.mp3"
  },
  "sim_retry": {
    text: "Almost there! Check the clues again.",
    style: "encouragement",
    file: "/assets/audio/sim_retry_almost_there_check_the_clues_again.mp3"
  },
  "reflect_1": {
    text: "What did you learn about understanding and representing problems? Explain it to Robo with an example!",
    style: "thinking",
    file: "/assets/audio/reflect_1_what_did_you_learn_about_understanding.mp3"
  },
  "reflect_done": {
    text: "Outstanding reflection! Lesson complete!",
    style: "celebration",
    file: "/assets/audio/reflect_done_outstanding_reflection_lesson_complete.mp3"
  }
};
